### ISSUE TITLE
Astrolytics GitHub Org

### ISSUE THREAD

**Issue by pomber** [scottclay/misc_code#1]
Hi @scottclay, sorry to open an issue on a random repo but I couldn't find another way to reach out.  

I was wondering if you are still using the [astrolytics](https://github.com/orgs/astrolytics) org. Because I'm building an app called astrolytics and would love to have an org with the same name so I can receive donations with [GitHub Sponsors + Open Collective](https://blog.opencollective.com/double-the-love/).

**Comment by scottclay** [comment]
Sorry @pomber, I'm afraid we have plans for astrolytics. Apologies!
